version: 0.3

phases:
  install:
   runtime-versions:
    python: 3.8
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - pytest
      - echo "Building the Flask application..."
      - python setup.py install
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app  
      
